package tech.vietinfo.services;

import javax.annotation.PostConstruct;
import javax.inject.Named;
import java.io.Serializable;
import java.util.*;

@Named("noiSanXuatService")
public class NoiSanXuatService implements Serializable {

    private static final long serialVersionUID = 1L;

    private Map<String, String> noiSanXuats;

    @PostConstruct
    public void init() {
        noiSanXuats = new HashMap<>();
        noiSanXuats.put("Ả Rập Xê Út", "Ả Rập Xê Út");
        noiSanXuats.put("Afghanistan", "Afghanistan");
        noiSanXuats.put("Ai Cập", "Ai Cập");
        noiSanXuats.put("Albania", "Albania");
        noiSanXuats.put("Algeria", "Algeria");
        noiSanXuats.put("Ấn Độ", "Ấn Độ");
        noiSanXuats.put("Andorra", "Andorra");
        noiSanXuats.put("Angola", "Angola");
        noiSanXuats.put("Anh", "Anh");
        noiSanXuats.put("Antigua và Barbuda", "Antigua và Barbuda");
        noiSanXuats.put("Áo", "Áo");
        noiSanXuats.put("Argentina", "Argentina");
        noiSanXuats.put("Armenia", "Armenia");
        noiSanXuats.put("Azerbaijan", "Azerbaijan");
        noiSanXuats.put("Ba Lan", "Ba Lan");
        noiSanXuats.put("Bắc Macedonia", "Bắc Macedonia");
        noiSanXuats.put("Bahamas", "Bahamas");
        noiSanXuats.put("Bahrain", "Bahrain");
        noiSanXuats.put("Bangladesh", "Bangladesh");
        noiSanXuats.put("Barbados", "Barbados");
        noiSanXuats.put("Belarus", "Belarus");
        noiSanXuats.put("Belize", "Belize");
        noiSanXuats.put("Bénin", "Bénin");
        noiSanXuats.put("Bhutan", "Bhutan");
        noiSanXuats.put("Bỉ", "Bỉ");
        noiSanXuats.put("Bờ Biển Ngà", "Bờ Biển Ngà");
        noiSanXuats.put("Bồ Đào Nha", "Bồ Đào Nha");
        noiSanXuats.put("Bolivia", "Bolivia");
        noiSanXuats.put("Bosnia và Herzegovina ", "Bosnia và Herzegovina");
        noiSanXuats.put("Botswana", "Botswana");
        noiSanXuats.put("Brazil", "Brazil");
        noiSanXuats.put("Brunei", "Brunei");
        noiSanXuats.put("Bulgaria", "Bulgaria");
        noiSanXuats.put("Burkina Faso", "Burkina Faso");
        noiSanXuats.put("Burundi", "Burundi");
        noiSanXuats.put("Các tiểu vương quốc Ả Rập Thống nhất", "Các tiểu vương quốc Ả Rập Thống nhất");
        noiSanXuats.put("Cameroon", "Cameroon");
        noiSanXuats.put("Campuchia", "Campuchia");
        noiSanXuats.put("Canada", "Canada");
        noiSanXuats.put("Cape Verde", "Cape Verde");
        noiSanXuats.put("Chad", "Chad");
        noiSanXuats.put("Chile", "Chile");
        noiSanXuats.put("Colombia", "Colombia");
        noiSanXuats.put("Comoros", "Comoros");
        noiSanXuats.put("Cộng hòa Congo", "Cộng hòa Congo");
        noiSanXuats.put("Cộng hòa dân chủ Congo", "Cộng hòa dân chủ Congo");
        noiSanXuats.put("Cộng hòa Dominican", "Cộng hòa Dominican");
        noiSanXuats.put("Cộng hòa Séc", "Cộng hòa Séc");
        noiSanXuats.put("Cộng hòa Trung Phi", "Cộng hòa Trung Phi");
        noiSanXuats.put("Costa Rica", "Costa Rica");
        noiSanXuats.put("Croatia", "Croatia");
        noiSanXuats.put("Cuba", "Cuba");
        noiSanXuats.put("Djibouti", "Djibouti");
        noiSanXuats.put("Dominica", "Dominica");
        noiSanXuats.put("Đài Loan", "Đài Loan");
        noiSanXuats.put("Đan Mạch", "Đan Mạch");
        noiSanXuats.put("Đông Timor", "Đông Timor");
        noiSanXuats.put("Đức", "Đức");
        noiSanXuats.put("Ecuador", "Ecuador");
        noiSanXuats.put("El Salvador", "El Salvador");
        noiSanXuats.put("Eritrea", "Eritrea");
        noiSanXuats.put("Estonia", "Estonia");
        noiSanXuats.put("Ethiopia", "Ethiopia");
        noiSanXuats.put("Fiji", "Fiji");
        noiSanXuats.put("Gabon", "Gabon");
        noiSanXuats.put("Gambia", "Gambia");
        noiSanXuats.put("Georgia", "Georgia");
        noiSanXuats.put("Ghana", "Ghana");
        noiSanXuats.put("Grenada", "Grenada");
        noiSanXuats.put("Guatemala", "Guatemala");
        noiSanXuats.put("Guinea", "Guinea");
        noiSanXuats.put("Guinea Xích đạo", "Guinea Xích đạo");
        noiSanXuats.put("Guinea-Bissau", "Guinea-Bissau");
        noiSanXuats.put("Guyana", "Guyana");
        noiSanXuats.put("Hà Lan", "Hà Lan");
        noiSanXuats.put("Haiti", "Haiti");
        noiSanXuats.put("Hàn Quốc", "Hàn Quốc");
        noiSanXuats.put("Hoa Kỳ", "Hoa Kỳ");
        noiSanXuats.put("Honduras", "Honduras");
        noiSanXuats.put("Hungary", "Hungary");
        noiSanXuats.put("Hy Lạp", "Hy Lạp");
        noiSanXuats.put("Iceland", "Iceland");
        noiSanXuats.put("Indonesia", "Indonesia");
        noiSanXuats.put("Iran", "Iran");
        noiSanXuats.put("Iraq", "Iraq");
        noiSanXuats.put("Ireland", "Ireland");
        noiSanXuats.put("Israel", "Israel");
        noiSanXuats.put("Jamaica", "Jamaica");
        noiSanXuats.put("Jordan", "Jordan");
        noiSanXuats.put("Kazakhstan", "Kazakhstan");
        noiSanXuats.put("Kenya", "Kenya");
        noiSanXuats.put("Kiribati", "Kiribati");
        noiSanXuats.put("Kosovo", "Kosovo");
        noiSanXuats.put("Kuwait", "Kuwait");
        noiSanXuats.put("Kyrgyzstan", "Kyrgyzstan");
        noiSanXuats.put("Lào", "Lào");
        noiSanXuats.put("Latvia", "Latvia");
        noiSanXuats.put("Lesotho", "Lesotho");
        noiSanXuats.put("Liban", "Liban");
        noiSanXuats.put("Liberia", "Liberia");
        noiSanXuats.put("Libya", "Libya");
        noiSanXuats.put("Liechtenstein", "Liechtenstein");
        noiSanXuats.put("Liên bang Micronesia", "Liên bang Micronesia");
        noiSanXuats.put("Lithuania", "Lithuania");
        noiSanXuats.put("Luxembourg", "Luxembourg");
        noiSanXuats.put("Ma-rốc", "Ma-rốc");
        noiSanXuats.put("Madagascar", "Madagascar");
        noiSanXuats.put("Malawi", "Malawi");
        noiSanXuats.put("Malaysia", "Malaysia");
        noiSanXuats.put("Maldives", "Maldives");
        noiSanXuats.put("Mali", "Mali");
        noiSanXuats.put("Malta", "Malta");
        noiSanXuats.put("Mauritania", "Mauritania");
        noiSanXuats.put("Mauritius", "Mauritius");
        noiSanXuats.put("Mexico", "Mexico");
        noiSanXuats.put("Moldova", "Moldova");
        noiSanXuats.put("Monaco", "Monaco");
        noiSanXuats.put("Mông Cổ", "Mông Cổ");
        noiSanXuats.put("Montenegro", "Montenegro");
        noiSanXuats.put("Mozambique", "Mozambique");
        noiSanXuats.put("Myanmar", "Myanmar");
        noiSanXuats.put("Na Uy", "Na Uy");
        noiSanXuats.put("Nam Phi", "Nam Phi");
        noiSanXuats.put("Nam Sudan", "Nam Sudan");
        noiSanXuats.put("Namibia", "Namibia");
        noiSanXuats.put("Nauru", "Nauru");
        noiSanXuats.put("Nepal", "Nepal");
        noiSanXuats.put("New Zealand", "New Zealand");
        noiSanXuats.put("Nga", "Nga");
        noiSanXuats.put("Nhật Bản", "Nhật Bản");
        noiSanXuats.put("Nicaragua", "Nicaragua");
        noiSanXuats.put("Niger", "Niger");
        noiSanXuats.put("Nigeria", "Nigeria");
        noiSanXuats.put("Oman", "Oman");
        noiSanXuats.put("Pakistan", "Pakistan");
        noiSanXuats.put("Palau", "Palau");
        noiSanXuats.put("Palestine", "Palestine");
        noiSanXuats.put("Panama", "Panama");
        noiSanXuats.put("Papua", "Papua");
        noiSanXuats.put("New Guinea", "New Guinea");
        noiSanXuats.put("Paraguay", "Paraguay");
        noiSanXuats.put("Peru", "Peru");
        noiSanXuats.put("Phần Lan", "Phần Lan");
        noiSanXuats.put("Pháp", "Pháp");
        noiSanXuats.put("Philippines", "Philippines");
        noiSanXuats.put("Qatar", "Berlin");
        noiSanXuats.put("Quần đảo Marshall", "Quần đảo Marshall");
        noiSanXuats.put("Quần đảo Solomon", "Quần đảo Solomon");
        noiSanXuats.put("Romania", "Romania");
        noiSanXuats.put("Rwanda", "Rwanda");
        noiSanXuats.put("Saint Kitts và Nevis", "Saint Kitts và Nevis");
        noiSanXuats.put("Saint Lucia", "Saint Lucia");
        noiSanXuats.put("Saint Vincent và Grenadines", "Saint Vincent và Grenadines");
        noiSanXuats.put("Samoa", "Samoa");
        noiSanXuats.put("San Marino", "San Marino");
        noiSanXuats.put("São Tomé và Príncipe", "São Tomé và Príncipe");
        noiSanXuats.put("Senegal", "Senegal");
        noiSanXuats.put("Serbia", "Serbia");
        noiSanXuats.put("Seychelles", "Seychelles");
        noiSanXuats.put("Sierra Leone", "Sierra Leone");
        noiSanXuats.put("Singapore", "Singapore");
        noiSanXuats.put("Síp", "Síp");
        noiSanXuats.put("Slovakia", "Slovakia");
        noiSanXuats.put("Slovenia", "Slovenia");
        noiSanXuats.put("Somalia", "Somalia");
        noiSanXuats.put("Sri Lanka", "Sri Lanka");
        noiSanXuats.put("Sudan", "Sudan");
        noiSanXuats.put("Suriname", "Suriname");
        noiSanXuats.put("Swaziland", "Swaziland");
        noiSanXuats.put("Syria", "Syria");
        noiSanXuats.put("Tajikistan", "Tajikistan");
        noiSanXuats.put("Tanzania", "Tanzania");
        noiSanXuats.put("Tây Ban Nha", "Tây Ban Nha");
        noiSanXuats.put("Thái Lan", "Thái Lan");
        noiSanXuats.put("Thành Vatican", "Thành Vatican");
        noiSanXuats.put("Thổ Nhĩ Kỳ", "Thổ Nhĩ Kỳ");
        noiSanXuats.put("Thụy Điển", "Thụy Điển");
        noiSanXuats.put("Thụy Sĩ", "Thụy Sĩ");
        noiSanXuats.put("Togo", "Togo");
        noiSanXuats.put("Tonga", "Tonga");
        noiSanXuats.put("Triều Tiên", "Triều Tiên");
        noiSanXuats.put("Trinidad và Tobago", "Trinidad và Tobago");
        noiSanXuats.put("Trung Quốc", "Trung Quốc");
        noiSanXuats.put("Tunisia", "Tunisia");
        noiSanXuats.put("Turkmenistan", "Turkmenistan");
        noiSanXuats.put("Tuvalu", "Tuvalu");
        noiSanXuats.put("Úc", "Úc");
        noiSanXuats.put("Uganda", "Uganda");
        noiSanXuats.put("Ukraine", "Ukraine");
        noiSanXuats.put("Uruguay", "Uruguay");
        noiSanXuats.put("Uzbekistan", "Uzbekistan");
        noiSanXuats.put("Vanuatu", "Vanuatu");
        noiSanXuats.put("Venezuela", "Venezuela");
        noiSanXuats.put("Việt Nam", "Việt Nam");
        noiSanXuats.put("Ý","Ý");
        noiSanXuats.put("Yemen", "Yemen");
        noiSanXuats.put("Zambia", "Zambia");
        noiSanXuats.put("Zimbabwe", "Zimbabwe");
    }

    public Map<String, String> getNoiSanXuats() {
        return noiSanXuats;
    }
}
