version: "3.9"

services:
  fashionshop-db:
    image: mysql:latest
    volumes:
      - ./init:/docker-entrypoint-initdb.d
      - db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: fashionshop_v5
      MYSQL_USER: fashionshopuser
      MYSQL_PASSWORD: 123456
    ports:
      - "13306:3306"
  fashionshop-app:
    depends_on:
      - fashionshop-db
    build:
      context: .
      dockerfile: Dockerfile-wildfly
    ports:
      - "18080:8080"
      - "19990:9990"
volumes:
  db_data: {}
